version: '3.1'

services:
        drupal:
                image: drupal:8-apache
                ports:
                        - 8080:80
                volumes:
                        - /var/www/html/modules
                        - /var/www/html/profiles
                        - /var/www/html/themes
                        - /var/www/html/sites
                depends_on:
                        - db
                restart: always
        db:
                image: mysql:5.7
                environment:
                        MYSQL_DATABASE: drupaldb
                        MYSQL_USER: mahek
                        MYSQL_PASSWORD: password 
                        MYSQL_ROOT_PASSWORD: rpassword 
                restart: always
